export const data = [
  {
    tennisClub: "Auckland West",
    startYear: 1968,
    totalMembers: 221,
    attendance: "68%",
    joiningFee: "$55",
  },
  {
    tennisClub: "Auckland Northshore",
    startYear: 1983,
    totalMembers: 155,
    attendance: "74%",
    joiningFee: "$65",
  },
  {
    tennisClub: "Tauranga",
    startYear: 1991,
    totalMembers: 136,
    attendance: "82%",
    joiningFee: "$70",
  },
  {
    tennisClub: "Whitianga",
    startYear: 1970,
    totalMembers: 72,
    attendance: "57%",
    joiningFee: "$45",
  },
  {
    tennisClub: "Hamilton",
    startYear: 1977,
    totalMembers: 154,
    attendance: "80%",
    joiningFee: "$60",
  },
  {
    tennisClub: "Taupo",
    startYear: 1959,
    totalMembers: 194,
    attendance: "83%",
    joiningFee: "$50",
  },
  {
    tennisClub: "Palmerston North",
    startYear: 1964,
    totalMembers: 200,
    attendance: "47%",
    joiningFee: "40",
  },
  {
    tennisClub: "Wellington",
    startYear: 1952,
    totalMembers: 427,
    attendance: "59%",
    joiningFee: "$70",
  },
  {
    tennisClub: "Picton",
    startYear: 1961,
    totalMembers: 88,
    attendance: "37%",
    joiningFee: "$35",
  },
  {
    tennisClub: "Nelson",
    startYear: 1965,
    totalMembers: 170,
    attendance: "79%",
    joiningFee: "$60",
  },
  {
    tennisClub: "Christchurch",
    startYear: 1955,
    totalMembers: 712,
    attendance: "61%",
    joiningFee: "$75",
  },
  {
    tennisClub: "Queenstown",
    startYear: 1969,
    totalMembers: 284,
    attendance: "60%",
    joiningFee: "$80",
  },
];
